Prelaunch fixes
Hyperobjekt/untd-site pull request #116
Opened 2021-06-17 19:52 UTC by touchRED

Notes: 

- Fixes header order in accordance with semantic guidelines
- Adds title to logo, making it accessible for screenreaders
- Adjusts tabindex for interactive items in the offscreen nav, turning them off when the nav is hidden
- Moves the offscreen nav into the `<nav>` element
- Adds `@reach/skip-nav` functionality
- Other small fixes here and there

2021-06-17 23:37 UTC, Lane requested changes
thanks for getting to these accessibility updates! a couple changes:

- [ ] re-add animations
- [ ] heading tag update on homepage

2021-06-17 23:37 UTC, Lane commented on src/pages/faq.js
> +              <h1><span>Frequently</span> <span>Asked</span> <span>Questions</span></h1>
the HTML semantics are good here, but i think James has tweaked these animations to his liking, so we should keep them.

2021-06-17 23:37 UTC, Lane commented on src/pages/index.js
>                <MDXRenderer>{cardData.cardHeading}</MDXRenderer>
these are set as heading level 4 in MDX frontmatter.  can we drop the heading 4 markdown in the frontmatter (`####`) and wrap this `MDXRenderer` in an `<h4>`?

2021-06-17 23:37 UTC, Lane commented on src/pages/pathways-to-mobility.js
> +              <h1><span>Pathways</span> <span>To</span> <span>Mobility</span></h1>
semantics are good, but we should keep animations.

2021-06-17 23:37 UTC, Lane commented on src/templates/research-topic.js
> +    )
noticing switch to 4 character indent here.  are you using prettier to autoformat?  if so it doesn't seem to be picking up on the `.prettierrc`.

2021-06-23 21:36 UTC, touchRED commented
@Lane not sure why it took me so long to notice that you had requested changes for this one – sorry about that! I believe I've addressed things as you intended – let me know if we're not quite there yet

2021-06-28 19:29 UTC, Lane commented
@touchRED sorry for the delay getting to this, can you fix up the conflicts?

2021-07-01 21:56 UTC, touchRED commented
@Lane fixed the conflict in `home.mdx` and thought I got the one in `package-lock.json` since my command line is saying everything is up to date, but Github seems to think differently.

Looks like we may need to merge and push master from the command line – wanted to check with you before pushing to master so let me know if you'd like me to do this!

2021-07-05 16:34 UTC, Lane commented
@touchRED went ahead and synced the `package-lock.json` and resolved some conflicts that came up from merging #122, going to merge this one up.

2021-07-05 16:34 UTC, Lane approved these changes

2021-07-05 16:35 UTC, merged