Contact Page and Email Subscribe
Hyperobjekt/untd-site pull request #44
Opened 2021-03-15 19:17 UTC by touchRED

Closes #11 and closes #31.

Notes: 

- The main addition here is the `subscribe` netlify function and its corresponding functionality in the footer and on the contact page
- The netlify function accepts an email and posts it to the list of leads in Salesforce. This might need a bit of work, but I wasn't sure how to proceed with QA locally since the function needs to be recognized by netlify. 
- The footer form is setup to use formik/yup as requested, and contains success/error transitions for feedback.

2021-03-15 22:39 UTC, lougroshek commented on netlify/functions/subscribe.js
> +        oid: "00D1U00000110AJ"
I *think* we probably want to store this in the `.env` file and pass it to the netlify function when we call it from the gatsby UI. That'll require changes to the build setup in netlify.toml

2021-03-15 22:54 UTC, lougroshek requested changes
@touchRED This looks great. 👍🏻  

* Please also uncomment and update the line in `netlify.toml` that tells Netlify there is a functions dir to build. 
* Client's `oid` in the netlify function will be exposed in the github repo, remove and access from `.env` file instead.
* I think it also makes sense to spend the time setting up [netlify dev](https://www.netlify.com/products/dev/) or [netlify-lambda](https://github.com/netlify/netlify-lambda) for local testing of the form at the same time. Mostly to cut down on having to deploy a bunch of times to test. 
* It looks like I didn't do this when I implemented this contact form previously, but we should have a honeypot in both forms and verify that it is not filled in before carrying out any submit actions. The honeypot field is in the contact form but (correct me if I'm wrong) I don't see it being handled by the form validation or the submit action. And I don't see one in the signup in the footer. This is important on Netlify because a bot could hit the site and push the client over their free limit. If we were using the default submit action for form handling, Netlify would detect and process the honeypot field, but because we're using JavaScript we need to check it ourselves. 

A few other UX comments: 
* I would love it if I could get a valid entry checkmark for the email input as well as the others. 
<img width="996" alt="Screen Shot 2021-03-15 at 5 50 19 PM" src="https://user-images.githubusercontent.com/746182/111231251-f079fa80-85b6-11eb-8c75-7ae5481c6711.png">

* I would love a spinner during form submission, maybe just right beside the submit button or inside of it, while the netlify function and then the contact form submit are processing. Have a look at this page: https://edopportunity.org/get-the-data/
* It seems like I get a success message even when the submit is clearly failing. 
<img width="1554" alt="Screen Shot 2021-03-15 at 5 48 49 PM" src="https://user-images.githubusercontent.com/746182/111231388-2ae39780-85b7-11eb-8b19-4395d3d2ba1a.png">

Other nit-picky stuff: 
* I'm wondering if we can disable the default validation for the footer signup and do validation like we do in the contact form instead? 
<img width="1126" alt="Screen Shot 2021-03-15 at 5 58 31 PM" src="https://user-images.githubusercontent.com/746182/111231956-21a6fa80-85b8-11eb-9586-dc63649c8730.png">
* I like the feedback on the footer submit form, but I find it a bit disorienting that the input completely disappears after I successfully submit. Can we have it persist and just change the styling a bit to suggest "disabled"? Maybe use a lighter gray for the underline and button? 
<img width="653" alt="Screen Shot 2021-03-15 at 5 59 21 PM" src="https://user-images.githubusercontent.com/746182/111232045-4d29e500-85b8-11eb-8a52-2e51c4978a22.png">



@laurendoone If Sasha has the cycles maybe we can have him look at styling the form inputs? If not, I think we should probably emulate the styling of the subscribe input for the simple text inputs (not the textarea).

2021-03-16 18:36 UTC, touchRED commented
@lougroshek added some more updates here – using `netlify dev` now as a develop command and everything seems to be working swimmingly – lmk where this should sit in our `package.json` commands, I'll be fixing up your other requested changes in the meantime! feel free to drop anything else here

2021-03-16 23:29 UTC, touchRED commented
@lougroshek some more updates, addressing the spinner, submission feedback/opacity, and validation behavior in the footer

2021-03-17 00:55 UTC, lougroshek commented
@touchRED Much improved! Thank you!

2021-03-25 15:48 UTC, merged